apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: staging
commonAnnotations:
  supported-by: sre@example.com
labels:
- includeSelectors: false
  pairs:
    project: instavote
patches:
- path: service.yaml
#- path: rollout.yaml

patchesStrategicMerge:
- |-
  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
  metadata:
    labels:
      app: vote
      tier: front
    name: vote
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: vote
    template:
      metadata:
        labels:
          app: vote
          tier: front
      spec:
        containers:
        - image: schoolofdevops/vote:v3
          name: vote

